# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodeguser',
            name='user',
        ),
        migrations.DeleteModel(
            name='LodegUser',
        ),
    ]
